spring.application.name=msvc-items
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
server.port=8002

# config para ver los colores en la consola
spring.output.ansi.enabled=always

# Vamos a comentar estas dos lineas, con eureka no serán necesarias, esto era manual y simple
# spring.cloud.discovery.client.simple.instances.msvc-products[0].uri=http://localhost:8001
# spring.cloud.discovery.client.simple.instances.msvc-products[1].uri=http://localhost:9001

# Esta es una configuración personalizada, no de spring
config.baseurl.endpoint.msvc-products=http://msvc-products

eureka.client.service-url.defaultZone=http://localhost:8761/eureka